import { Hono } from 'hono'

const app = new Hono()

async function authMiddleware(c:any, next:any) {
  if(c.req.header("Authorization")){
    await next()
  }else{
    return c.text("You dont have Access");
  }
}

app.get(authMiddleware)

app.get('/', async (c) => {
  const html = `
  <!DOCTYPE html>
    <body>
      <h1>Hello World</h1>
      <p>This markup was generated by a Cloudflare Worker.</p>
    </body>
`;
  
  return new Response(html,{
    headers: {
      "content-type": "text/html;charset=UTF-8",
    },  
  })
})

app.post('/user', (c) => {
  return c.text('Hello Hono!')
})

export default app
